### ISSUE TITLE
Installation error?

### ISSUE THREAD

**Issue by fglaser** [KosinskiLab/alphafold3x#1]
Dear Prof. Kosinski,

This is really a wonderful addition!

I would like very much to try it, and I think the suggested installation procedure produced no error message, but when I tried to run your example, I got the following error pasted below. I understand it does not recognize the crosslink key, and I am not sure how to proceed.

Just as a test, when I remove the crosslink section, alphafold3 runs perfectly well. Maybe I am doing a trivial mistake and some directory of alphafold3x needs to be added to some location in alphafold3 installation?

Thanks a lot in advance, and again great addition!

Fabian
Technion, Israel

bash test2.sh
I1208 09:34:03.112920 140226657427456 folding_input.py:1046] Detected /root/af_input/test2.json is an AlphaFold 3 JSON since the top-level is not a list.
Traceback (most recent call last):
File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1052, in load_fold_inputs_from_path
fold_inputs.append(Input.from_json(json_str))
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 667, in from_json
_validate_keys(
File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 43, in _validate_keys
raise ValueError(f'Unexpected JSON keys in: {", ".join(sorted(bad_keys))}')
ValueError: Unexpected JSON keys in: crosslinks

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/app/alphafold/run_alphafold.py", line 716, in
app.run(main)
File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
^^^^^^^^^^
File "/app/alphafold/run_alphafold.py", line 613, in main
fold_inputs = folding_input.load_fold_inputs_from_path(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py", line 1054, in load_fold_inputs_from_path
raise ValueError(
ValueError: Failed to load fold input from /root/af_input/test2.json. The JSON at /root/af_input/test2.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.

**Comment by jkosinski** [comment]
Hi Fabian, it indeed does look like an installation issue. Could it be the /alphafold3_venv/lib/python3.11/site-packages/alphafold3/common/folding_input.py file seems to be from the original AlphaFold3 rather than AF3x? You need to make sure you have no global AlphaFold3 installed, no AlphaFold3 in pythonpath. For us works well with the Mamba installation package.

**Comment by fglaser** [comment]
Hi, sorry to bother again,

AF3 is locally installed, I am not sure if I am doing right, I tried to run the docker from within alphafold3x, while it seems to run correctly, at least no errors, then when I ttry the replace the docker container to alphafold3x, it gives a different errores with a standard run.

I just paste the installation process output, the docker bash and and the final error I get, I would be very grateful if you could take a look.

Fabian 



docker build -t alphafold3x -f docker/Dockerfile .


[+] Building 645.3s (16/16) FINISHED                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                                 0.0s
 => => transferring dockerfile: 3.13kB                                                                                                               0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:12.6.0-base-ubuntu22.04                                                                       1.4s
 => [internal] load .dockerignore                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                      0.0s
 => [ 1/11] FROM docker.io/nvidia/cuda:12.6.0-base-ubuntu22.04@sha256:5dca947f477ec8ea91624447bdad7cc5f6a0dfe038ef53642c884bf5416478a6               0.0s
 => [internal] load build context                                                                                                                    0.7s
 => => transferring context: 168.71MB                                                                                                                0.7s
 => CACHED [ 2/11] RUN apt update --quiet     && apt install --yes --quiet software-properties-common     && apt install --yes --quiet git wget gcc  0.0s
 => CACHED [ 3/11] RUN add-apt-repository ppa:deadsnakes/ppa     && DEBIAN_FRONTEND=noninteractive apt install --yes --quiet python3.11 python3-pip  0.0s
 => CACHED [ 4/11] RUN python3.11 -m venv /alphafold3_venv                                                                                           0.0s
 => CACHED [ 5/11] RUN pip3 install --upgrade pip                                                                                                    0.0s
 => CACHED [ 6/11] RUN mkdir /hmmer_build /hmmer ;     wget http://eddylab.org/software/hmmer/hmmer-3.4.tar.gz --directory-prefix /hmmer_build ;     0.0s
 => [ 7/11] COPY . /app/alphafold                                                                                                                    0.7s
 => [ 8/11] WORKDIR /app/alphafold                                                                                                                   0.0s
 => [ 9/11] RUN pip3 install -r dev-requirements.txt                                                                                               236.4s
 => [10/11] RUN pip3 install --no-deps .                                                                                                           351.5s
 => [11/11] RUN build_data                                                                                                                          33.0s
 => exporting to image                                                                                                                              21.4s
 => => exporting layers                                                                                                                             21.4s
 => => writing image sha256:df9a407cfd08e2578f373b9e9ce7b8f51b36fe8b1d3e22ecb322da531a1546ea                                                         0.0s

docker run -it \
    --volume ./af_input:/root/af_input \
    --volume ./af_output:/root/af_output \
    --volume /home/fabian/alphafold3x:/root/models \
    --volume /data/databases:/root/public_databases \
    --gpus '"device=1"' \
    alphafold3x \
    python run_alphafold.py \
    --json_path=/root/af_input/test2.json \
    --model_dir=/root/models \
    --output_dir=/root/af_output
~

bash test2.sh
I1209 07:08:05.809547 140100668829696 folding_input.py:1229] Detected /root/af_input/test2.json is an AlphaFold 3 JSON since the top-level is not a list.
I1209 07:08:06.738151 140100668829696 xla_bridge.py:895] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I1209 07:08:06.739101 140100668829696 xla_bridge.py:895] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
Running AlphaFold 3. Please note that standard AlphaFold 3 model parameters are
only available under terms of use provided at
https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md.
If you do not agree to these terms and are using AlphaFold 3 derived model
parameters, cancel execution of AlphaFold 3 inference with CTRL-C, and do not
use the model parameters.
Found local devices: [CudaDevice(id=0)]
Building model from scratch...
Processing 1 fold inputs.
Processing fold input test2
Checking we can load the model parameters...
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 947, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 931, in main
    process_fold_input(
  File "/app/alphafold/run_alphafold.py", line 616, in process_fold_input
    _ = model_runner.model_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 338, in model_params
    return params.get_model_haiku_params(model_dir=self._model_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/params.py", line 204, in get_model_haiku_params
    model_files, is_compressed = select_model_files(model_dir)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/params.py", line 198, in select_model_files
    raise FileNotFoundError(f'No models matched in {model_dir}')
FileNotFoundError: No models matched in /root/models

**Comment by jkosinski** [comment]
Hi, this again seems like AlphaFold installation issue - "FileNotFoundError: No models matched in /root/models" might mean that the AF3 weights that should be in that path are missing. You need to downloaded separately according to AF3 instructions. Since you use --volume /home/fabian/alphafold3x:/root/models, i guess you need to put the weights in /home/fabian/alphafold3x.

**Comment by fglaser** [comment]
Yes I corrected the location of the weights and it worked!

Thanks a lot, I would certainly try your great addition.

Regards,
Fabian
